# Generated by Django 2.2.6 on 2019-11-20 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
