# Generated by Django 2.2.6 on 2019-11-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=50)),
                ('app', models.ManyToManyField(related_name='app_language', to='app.App')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='language',
            field=models.ManyToManyField(related_name='app_language', to='app.Language'),
        ),
    ]
