# Generated by Django 2.2.6 on 2019-11-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191117_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
