# Generated by Django 2.2.6 on 2019-11-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191124_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developer_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
